#!/bin/bash

clear
echo -en "\n\n1. Saving Account \n2. Current Account\n\nEnter Your Choice : "
read ca

case ca in

1)
cd ./accounts/saving
clear
echo -en "\nEnter Account No : "
read accno
mv $accno ./savdel




cd ../..
;;

2)
cd ./accounts/current
clear
echo -en "\nEnter Account No : "
read accno
mv $accno ./currdel




cd ../..
;;

*)
echo -e "\n\nInvalid Input "
read gap
;;
