#! /bin/bash

clear
bcode=9123

count=$(tail -1 './accounts/saving/savno')

type='Saving'
echo -e "\n\tEnter Details"


echo -en "\nEnter First Name : "
read fname

echo -en "\nEnter Last Name : "
read lname

echo -en "\nEnter Address : "
read ad

echo -en "\nEnter Date of Birth (dd/mm/yyyy) : "
read dob

echo -en "\nEnter Aadhar No : "
read adh

echo -en "\nEnter Email : "
read email

echo -en "\nEnter Mobile No : "
read ph

echo -en "\nEnter Bal : "
read bal

echo -en "\nEnter Password : "
read pas

accno=$(((bcode*1000000000)+count))

cd ./accounts/saving

touch $accno

echo -en "$accno\n$type\n$pas\n$fname $lname\n$ad\n$dob\n$adh\n$email\n$ph\n$bal" > $accno

count=$((count+1))
echo -e "\n Account No : $accno "

echo "$count" > savno
echo -e "$accno\t$fname $lname\t$dob\t$ph\t$email" >> savacc

echo -e "Congratulations $fname $lname your Account has been open Sucessfully \n\nAccouunt No : $accno\nDOB : $dob\nEmail : $email\nPhone No : $ph\nBalance : $bal \nDefault Password : $pas\n" | mail -s "Account Opened Sucessfully" $email

cd ../..


