#! /bin/bash

clear

echo -en "\n\tView List Menu\n\n1. Savings Account List\n2. Current Account List\n\nEnter your Choice : "
read c
case $c in 
1)
clear
cd ./accounts/saving
echo -e "\n\tSavings Accounts List\n\nAccount No\tName\t\tDOB\t\tPhone NO\tEmail ID"
cat savacc
read gap
cd ../..
;;
2)
clear
cd ./accounts/current
echo -e "\n\tCurrent Accounts List\n\nAccount No\tName\t\tDOB\t\tPhone NO\tEmail ID"
cat curracc
read gap
cd ../..
;;
*)
echo -e "Oops Wrong Choice "
read gap;
;;
esac

