#! /bin/bash

clear
echo -e "\n\tWelcome to Admin Menu\n"
echo -e "\n1. Add Accounts \n2. Edit Accounts \n3. Veiw Account \n4. View All Accounts \n5. Delete Account \n"
echo -n "Enter Your Choice : "
read choice 

case $choice in

1)
./add;;

2)
./edit ;;

3)
./view ;;

4)
./list ;;

5) 
./delete ;;

*)
echo -e "\nLogin Again \n\n"
echo "Press any Key for Exit"
read gap
 ;; 

esac
