#! /bin/bash



e=1;
while [$e -eq 1]
do
clear
echo -en "\n\t Customer Menu\n\n1. View Details\n2. Debit \n3. Credit \n4. Change Password \n5.Logout \n\nEnter Your Choice : "
read s
case s in

1)
;;

2);;

3);;

4)
;;

5)
e=2;;

*)
echo -e "\nOops!! Invalid Input" ;;
esac
done
