#! /bin/bash

clear
	echo -en "\n\t              _     _                                     _   "
	echo -en "\n\t     /\      | |   | |     /\                            | |  "
	echo -en "\n\t    /  \   __| | __| |    /  \   ___ ___ ___  _   _ _ __ | |_ "
	echo -en "\n\t   / /\ \ / _  |/ _  |   / /\ \ / __/ __/ _ \| | | |  _ \| __|"
	echo -en "\n\t  / ____ \ (_| | (_| |  / ____ \ (_| (_| (_) | |_| | | | | |_ "
	echo -en "\n\t /_/    \_\____|\____| /_/    \_\___\___\___/ \____|_| |_|\__|"
case $1 in
Saving)
bcode=9123
count=$(tail -1 './savno')
type='Saving'
;;

Current)

bcode=9124
count=$(tail -1 './currno')
type='Current'
;;

esac

echo -e "\n\n\tEnter Details"


echo -en "\nEnter First Name : "
read fname

echo -en "\nEnter Last Name : "
read lname

echo -en "\nEnter Address : "
read ad

echo -en "\nEnter Date of Birth (dd/mm/yyyy) : "
unset dob
k=1
while [[ ! $dob =~ ^(0[1-9]|[1-2][0-9]|3[0-1])[-/.](0[1-9]|1[0-2])[-/.][0-9]{4}$ ]];
do
	if [ $k -gt 1 ] ;
	then
	echo -en "\nEnter Correct DOB : "
	fi
	read dob
	let "k=k+1"
done

echo -en "\nEnter Aadhar No : "
unset adh
k=1
while [[ ! $adh =~ ^[0-9]{12}$ ]];
do
	if [ $k -gt 1 ] ;
	then
	echo -en "\nEnter Correct Aadhaar No : "
	fi
	read adh
	let "k=k+1"
done

echo -en "\nEnter Email : "
read email

echo -en "\nEnter Mobile No : "
unset ph
k=1
while [[ ! $ph =~ ^[1-9][0-9]{9}$ ]];
do
	if [ $k -gt 1 ] ;
	then
	echo -en "\nEnter Correct Phone No : "
	fi
	read ph
	let "k=k+1"
done

echo -en "\nEnter Bal : "
read bal

echo -en "\nEnter Password : "
read pas

let "accno = (bcode*1000000000) + count "
let "mon = (100000000000000) + accno "

echo -en "$accno\n$type\n$pas\n$fname $lname\n$ad\n$dob\n$adh\n$email\n$ph\n" > ./accounts/$accno
echo -en "$bal" > ./accounts/balance/$mon
let "count++"
case $1 in

Saving)

echo "$count" > ./savno
echo -e "$accno\t$fname $lname" >> ./savacc
;;

Current)

echo "$count" > ./currno
echo -e "$accno\t$fname $lname" >> ./curracc
;;
esac


echo -e "\nAccount No : $accno \n\nWait For 1 minute"
echo -e "Congratulations $fname $lname , Your Account has been Opened Sucessfully \n\nAccouunt No : $accno\nDOB : $dob\nEmail : $email\nPhone No : $ph\nBalance : $bal \nDefault Password : $pas\n\nFor Further Enquires ,Please Visit Branch\nThank-you For Choosing Our Bank\n\n\n*****This Mail is Automatically Generated *****" | mail -s "Bank Account Opened Sucessfully" $email
echo -e "\n\nAccount has been Opened Sucessfully"
echo -e "\nPress Any Key To Continue "
read gap

