#!/bin/bash

clear
echo -en "\n\tDelete Menu \n\n1. Delete Account \n2. View Deleted Accounts \nEnter your Choice : "
read cv 

case $cv in
1)
cd ./accounts
echo -en "\nEnter Account No : "
read accno

if [ -f "$accno" ];
then
type=$( head -2 $accno | tail -n +2 )
mv $accno ../del
let "mon = (100000000000000) + accno "
mv ./balance/$mon ../del/$mon
cd ..

case $type in

Saving)
sed '/$accno/p' ./savacc  >> ./savdel
# sed '/^$/d' ./savdel
echo "$(sed '/$accno/d' ./savacc )" > ./savacc
echo "$(sed '/^$/d' ./savacc)" > ./savacc
;;

Current)
sed '/$accno/p' ./curracc  >> ./currdel
# sed '/^$/d' ./currdel
echo "$(sed '/$accno/d' ./curracc )" > ./curracc
echo "$(sed '/^$/d' ./curracc )" > ./curracc 
;;
*)
;;
esac
echo -en "\n\nAccount Deleted Sucessfully \n"
echo -e "\nPress Any Key To Continue "
read gap
else
echo -en "\n\nOops!! Account Not Found \n"
echo -e "\nPress Any Key To Continue "
read gh
fi

;;

2)
clear
echo -en "\n\tDeleted Account List Menu\n\n1. Savings Account List\n2. Current Account List\n\nEnter your Choice : "
read c
case $c in 
1)
clear
echo -e "\n\tSavings Accounts List\n\nAccount No\tName"
cat ./savdel
echo -e "\nPress Any Key To Continue "
read gap
;;
2)
clear
echo -e "\n\tCurrent Accounts List\n\nAccount No\tName"
cat ./currdel
echo -e "\nPress Any Key To Continue "
read gap
;;
esac
;;
*)
echo -n "\n\nOops!! Wrong Choice " 
echo -e "\nPress Any Key To Continue "
read gap
;;
esac
