#! /bin/bash

clear

echo -en "\n\t __      ___                 _      _     _     __  __                  "
echo -en "\n\t \ \    / (_)               | |    (_)   | |   |  \/  |                 "
echo -en "\n\t  \ \  / / _  _____      __ | |     _ ___| |_  | \  / | ___ _ __  _   _ "
echo -en "\n\t   \ \/ / | |/ _ \ \ /\ / / | |    | / __| __| | |\/| |/ _ \ '_ \| | | |"
echo -en "\n\t    \  /  | |  __/\ V  V /  | |____| \__ \ |_  | |  | |  __/ | | | |_| |"
echo -en "\n\t     \/   |_|\___| \_/\_/   |______|_|___/\__| |_|  |_|\___|_| |_|\__,_|"
echo -en "\n\n\n1. Savings Account List\n2. Current Account List\n\nEnter your Choice : "
read c
case $c in 
1)
clear
echo -en "\n\t   _____             _                                                     _         _      _     _   "
echo -en "\n\t  / ____|           (_)                     /\                            | |       | |    (_)   | |  "
echo -en "\n\t | (___   __ ___   ___ _ __   __ _ ___     /  \   ___ ___ ___  _   _ _ __ | |_ ___  | |     _ ___| |_ "
echo -en "\n\t  \___ \ / _  \ \ / / |  _ \ / _  / __|   / /\ \ / __/ __/ _ \| | | |  _ \| __/ __| | |    | / __| __|"
echo -en "\n\t  ____) | (_| |\ V /| | | | | (_| \__ \  / ____ \ (_| (_| (_) | |_| | | | | |_\__ \ | |____| \__ \ |_ "
echo -en "\n\t |_____/ \__,_| \_/ |_|_| |_|\__, |___/ /_/    \_\___\___\___/ \__,_|_| |_|\__|___/ |______|_|___/\__|"
echo -en "\n\n\nAccount No\tName\n\n"
cat ./savacc
echo -e "\n\nPress Any Key To Continue "
read gap
;;
2)
clear
echo -en "\n\t   _____                          _                                       _         _      _     _   "
echo -en "\n\t  / ____|                        | |       /\                            | |       | |    (_)   | |  "
echo -en "\n\t | |    _   _ _ __ _ __ ___ _ __ | |_     /  \   ___ ___ ___  _   _ _ __ | |_ ___  | |     _ ___| |_ "
echo -en "\n\t | |   | | | | '__| '__/ _ \ '_ \| __|   / /\ \ / __/ __/ _ \| | | | '_ \| __/ __| | |    | / __| __|"
echo -en "\n\t | |___| |_| | |  | | |  __/ | | | |_   / ____ \ (_| (_| (_) | |_| | | | | |_\__ \ | |____| \__ \ |_ "
echo -en "\n\t  \_____\__,_|_|  |_|  \___|_| |_|\__| /_/    \_\___\___\___/ \__,_|_| |_|\__|___/ |______|_|___/\__|"
echo -en "\n\n\nAccount No\tName\n\n"
cat ./curracc
echo -e "\n\nPress Any Key To Continue "
read gap
;;
*)
echo -e "\n\nOops Wrong Choice "
echo -e "Press Any Key To Continue "
read gap
;;

 




























esac



