#! /bin/bash

clear

echo -en "\n\tView List Menu\n\n1. Savings Account List\n2. Current Account List\n\nEnter your Choice : "
read c
case $c in 
1)
clear
echo -e "\n\tSavings Accounts List\n\nAccount No\tName"
cat ./savacc
read gap
;;
2)
clear
echo -e "\n\tCurrent Accounts List\n\nAccount No\tName"
cat ./curracc
read gap
;;
*)
echo -e "Oops Wrong Choice "
read gap;
;;
esac

