#! /bin/bash

j=1
while [ $j -eq 1 ]
do
clear

echo -e "\n\tWelcome to Admin Menu\n"
echo -e "\n1. Add Accounts \n2. Edit Accounts \n3. Veiw Account \n4. View All Accounts \n5. Delete Account \n6. Exit\n"
echo -n "Enter Your Choice : "
read choice 
case $choice in

1)
echo -ne "\n\n\tAdd \n1. Saving Account \n2. Current Account\n\nEnter Your Choice : "
read c

case $c in
1) 
./addacc Saving
;;

2) 
./addacc Current
;;

*)
echo "Sorry,Wrong Input";;
esac
./add;;

2)
./adedit ;;

3)
echo -en "\n\nEnter Account No : " 
read accc
cd ./accounts
./custview $accc
cd ..
;;
4)
./adlist ;;

5) 
./addel ;;

6)
j=2;;

*)
echo -en "\nInvalid Input\t"
echo -e "\nPress Any Key To Continue "
read gap
 ;; 

esac

done
