#! /bin/bash

j=1
while [ $j -eq 1 ]
do
clear

echo -en "\n\t __          __  _                            _                      _           _         __  __                  "
echo -en "\n\t \ \        / / | |                          | |            /\      | |         (_)       |  \/  |                 "
echo -en "\n\t  \ \  /\  / /__| | ___ ___  _ __ ___   ___  | |_ ___      /  \   __| |_ __ ___  _ _ __   | \  / | ___ _ __  _   _ "
echo -en "\n\t   \ \/  \/ / _ \ |/ __/ _ \|  _   _ \ / _ \ | __/ _ \    / /\ \ / _  |  _   _ \| |  _ \  | |\/| |/ _ \  _ \| | | |"
echo -en "\n\t    \  /\  /  __/ | (_| (_) | | | | | |  __/ | || (_) |  / ____ \ (_| | | | | | | | | | | | |  | |  __/ | | | |_| |"
echo -en "\n\t     \/  \/ \___|_|\___\___/|_| |_| |_|\___|  \__\___/  /_/    \_\__,_|_| |_| |_|_|_| |_| |_|  |_|\___|_| |_|\____|"

echo -e "\n\n\n1. Add Accounts \n2. Edit Accounts \n3. Veiw Account \n4. View All Accounts \n5. Delete Account \n6. Forms \n7. Exit\n"
echo -n "Enter Your Choice : "
read choice 
case $choice in

	1)
	clear
	echo -en "\n\t              _     _                                     _   "
	echo -en "\n\t     /\      | |   | |     /\                            | |  "
	echo -en "\n\t    /  \   __| | __| |    /  \   ___ ___ ___  _   _ _ __ | |_ "
	echo -en "\n\t   / /\ \ / _  |/ _  |   / /\ \ / __/ __/ _ \| | | |  _ \| __|"
	echo -en "\n\t  / ____ \ (_| | (_| |  / ____ \ (_| (_| (_) | |_| | | | | |_ "
	echo -en "\n\t /_/    \_\____|\____| /_/    \_\___\___\___/ \____|_| |_|\__|"
	echo -ne "\n\n\n1. Saving Account \n2. Current Account\n\nEnter Your Choice : "
	read c

		case $c in
		1) 
		./addacc Saving
		;;

		2) 
		./addacc Current
		;;

		*)
		echo -e "\nOops!!! Wrong Input. \nPress Any Key To Continue "
		read gap;;
		esac
	;;

	2)
		./adedit ;;

	3)
		clear
		echo -en "\n\t __      ___                                                   _  " 
		echo -en "\n\t \ \    / (_)                   /\                            | |  "
		echo -en "\n\t  \ \  / / _  _____      __    /  \   ___ ___ ___  _   _ _ __ | |_ "
		echo -en "\n\t   \ \/ / | |/ _ \ \ /\ / /   / /\ \ / __/ __/ _ \| | | | '_ \| __|"
		echo -en "\n\t    \  /  | |  __/\ V  V /   / ____ \ (_| (_| (_) | |_| | | | | |_ "
		echo -en "\n\t     \/   |_|\___| \_/\_/   /_/    \_\___\___\___/ \__,_|_| |_|\__|"
		echo -en "\n\n\nEnter Account No : " 
		read accc
		cd ./accounts
		./custview $accc
		cd ..
	;;
	4)
		./adlist ;;

	5) 
		./addel ;;

	6)
		./formlist
	;;

	7)
	j=2;;

	*)
	echo -en "\nInvalid Input!!! \nPress Any Key To Continue "
	read gap
	 ;; 

esac

done








