#! /bin/bash

clear
echo -e "\n\tCustomer Menu\n\n1. Login Account \n2. Account Opening Form \n3. Exit\n"
echo -n "Enter Your Choice : "
read choice 

case $choice in

1)
./log 
;; 

2)
 
;;

3)

;;

*)
echo -en "Oops!! Invalid Input "
echo -e "\nPress Any Key To Continue "
read gap
;;

esac
