#! /bin/bash 

clear
echo -en "\n\n\tForget Password\n\nEnter Your Account No : "
read acc
cd ./accounts
if [ -f "$acc" ];
then
echo -en "You have requested for password\nYour Password : $(head -n 3 $acc | tail -n +3 )" | mail -s "Password Requested" $(head -n 8 $acc | tail -n +8 ) | echo -e "\nEmail has been send to your registered email ID\nThank-you"
read gap 
else
echo -e "\nOops!! Account Not Found"
read gap
fi 
 
