#!/bin/bash

clear


echo -en "\n\t  _   _                                                   _     ______                   "
echo -en "\n\t | \ | |                   /\                            | |   |  ____|                  "
echo -en "\n\t |  \| | _____      __    /  \   ___ ___ ___  _   _ _ __ | |_  | |__ ___  _ __ _ __ ___  "
echo -en "\n\t | .   |/ _ \ \ /\ / /   / /\ \ / __/ __/ _ \| | | |  _ \| __| |  __/ _ \|  __|  _   _ \ "
echo -en "\n\t | |\  |  __/\ V  V /   / ____ \ (_| (_| (_) | |_| | | | | |_  | | | (_) | |  | | | | | |"
echo -en "\n\t |_| \_|\___| \_/\_/   /_/    \_\___\___\___/ \__,_|_| |_|\__| |_|  \___/|_|  |_| |_| |_|"

echo -e "\n\n\n\tEnter Details"

echo -en "\nEnter First Name : "
read fname

echo -en "\nEnter Last Name : "
read lname

echo -en "\nEnter Address : "
read ad

echo -en "\nEnter Date of Birth (dd/mm/yyyy) : "
unset dob
k=1
while [[ ! $dob =~ ^(0[1-9]|[1-2][0-9]|3[0-1])[-/.](0[1-9]|1[0-2])[-/.][0-9]{4}$ ]];
do
	if [ $k -gt 1 ] ;
	then
		echo -en "\nEnter Correct DOB : "
	fi
	read dob
	let "k=k+1"
done

echo -en "\nEnter Aadhar No : "
unset adh
k=1
while [[ ! $adh =~ ^[0-9]{12}$ ]];
do
	if [ $k -gt 1 ] ;
	then
	echo -en "\nEnter Correct Aadhaar No : "
	fi
	read adh
	let "k=k+1"
done

echo -en "\nEnter Email : "
read email

echo -en "\nEnter Mobile No : "
unset ph
k=1
while [[ ! $ph =~ ^[1-9][0-9]{9}$ ]];
do
	if [ $k -gt 1 ] ;
	then
	echo -en "\nEnter Correct Phone No : "
	fi
	read ph
	let "k=k+1"
done

echo -en "\nSelect Account Type : \n1. Saving\n2. Current  : "
read tp
case $tp in
1)
typ="Saving";;
2)
typ="Current";;
esac

echo -en "\nEnter Password : "
read -s pas
echo -e "\n\nWait For 1 minute"

rd=$RANDOM

let "tok=2345+rd"
echo -en "\n$typ\n$pas\n$fname $lname\n$ad\n$dob\n$adh\n$email\n$ph\n" > ./forms/$tok 
echo -e "$tok | $fname $lname" >> ./foracc
echo -e "\n\nWait for 1min "
echo -e "Dear $fname $lname ,\nYour New Account Opening Application $tok is in process.Kindly Visit your nearest branch for Physical Verification with your documents.\n\n\n\nFor Further Enquires ,Please Visit Branch\nThank-you For Choosing Our Bank\n\n\n*****This Mail is Automatically Generated *****" | mail -s "New Bank Account Form Details" $email
echo -e "\nYour Token No : $tok \n\nPress Any Key To Continue "
read gap



