#!/bin/bash

i=1
while [ $i -eq 1 ]
do
clear

echo -ne "\n\t  __  __       _         __  __                  "
echo -ne "\n\t |  \/  |     (_)       |  \/  |                 "
echo -ne "\n\t | \  / | __ _ _ _ __   | \  / | ___ _ __  _   _ "
echo -ne "\n\t | |\/| |/ _  | |  _  | | |\/| |/ _ \  _ \| | | |"
echo -ne "\n\t | |  | | (_| | | | | | | |  | |  __/ | | | |_| |"
echo -ne "\n\t |_|  |_|\____|_|_| |_| |_|  |_|\___|_| |_|\__,_|"
echo -ne "\n\n1. Admin \n2. Customer \n3. Exit\n\nEnter Your Choice : "
read v 

	case $v in

	1)
		clear
		echo -ne "\n\nEnter Admin Password : "
		read -s pass
		if [ $pass == "admin" ]
		then
		./admin
		else
		echo -e "\n\nWrong Password \n\n"
		echo -n "Press any Key for Exit"
		read gap
		fi 
	;;

	2)
		./custmenu ;;

	3)
		i=2
		echo -e "\nThankyou Visit Again\n\n"
		echo -e "\nPress Any Key To Continue "
		read gap
	 ;; 

	*)
		echo -e "\nOops!! Invalid Input"
		echo -e "\nPress Any Key To Continue "
		read gap
	;;

	esac

done





                                                                                  

                                                                                  
                                                                                 

