#! /bin/bash


rm -r accounts/balance
rm savacc savno savdel curracc currno currdel
mkdir accounts
mkdir accounts/balance

mkdir del
touch savacc savno savdel
chmod +770 savacc savno savdel
echo -n "2" > savno

touch curracc currno currdel
chmod +770 curracc currno currdel
echo -n "2" > currno

