#! /bin/bash


rm -r accounts
rm -r del
rm savacc savno savdel curracc currno currdel
mkdir accounts
mkdir accounts/balance

cp viewcust ./accounts
cp menulog ./accounts

mkdir del
touch savacc savno savdel curracc currno currdel
chmod +770 savacc savno savdel curracc currno currdel
echo -n "2" > savno
echo -n "2" > currno

cd ./accounts 
mv viewcust custview
mv menulog logmenu
cd ..
read gap
