#! /bin/bash

clear
echo -en "\n\tEdit Menu \n\n1. Password \n2. Name \n3. Address \n4. DOB \n5. Aadhar \n6. Email \n7. Phone No \n8. Exit \nEnter Your Choice : "  
read cq
case $cq in

	1)
		r=3
		let "r--"
		echo "$(head -$r $1)" > temp
		let "r=r+2"
		clear
		echo -en "\nEnter New Password : " 
		read pas
		echo "$pas" >> temp
		echo "$(tail +$r $1)" >> temp
		echo -e "\n\nDetails Updated "
		echo -e "\n\nPress Any Key To Continue "
		read ge
		;;
	2)
		r=4
		let "r--"
		echo "$(head -$r $1)" > temp
		let "r=r+2"
		clear
		echo -en "\nEnter New Name : " 
		read ad
		echo "$ad" >> temp
		echo "$(tail +$r $1)" >> temp
		echo -e "\n\nDetails Updated "
		echo -e "\n\nPress Any Key To Continue "
		read ge
		;;

	3)
		r=5
		let "r--"
		echo "$(head -$r $1)" > temp
		let "r=r+2"
		clear
		echo -en "\nEnter New Address : " 
		read ad
		echo "$ad" >> temp
		echo "$(tail +$r $1)" >> temp
		echo -e "\n\nDetails Updated "
		echo -e "\n\nPress Any Key To Continue "
		read ge
		;;

	4)
		r=6
		let "r--"
		echo "$(head -$r $1)" > temp
		let "r=r+2"
		clear
		echo -en "\nEnter New DOB : " 
		read dob
		echo "$dob" >> temp
		echo "$(tail +$r $1)" >> temp
		echo -e "\n\nDetails Updated "
		echo -e "\n\nPress Any Key To Continue "
		read ge
		;;

	5)
		r=7
		let "r--"
		echo "$(head -$r $1)" > temp
		let "r=r+2"
		clear
		echo -en "\nEnter New Aadhar : " 
		read adh
		echo "$adh" >> temp
		echo "$(tail +$r $1)" >> temp
		echo -e "\n\nDetails Updated "
		echo -e "\n\nPress Any Key To Continue "
		read ge
	;;

	6)
		r=8
		let "r--"
		echo "$(head -$r $1)" > temp
		let "r=r+2"
		clear
		echo -en "\nEnter New Email : " 
		read email
		echo "$email" >> temp
		echo "$(tail +$r $1)" >> temp
		echo -e "\n\nDetails Updated "
		echo -e "\n\nPress Any Key To Continue "
		read ge
	;;

	7)
		r=9
		let "r--"
		echo "$(head -$r $1)" > temp
		let "r=r+2"
		clear
		echo -en "\nEnter New Phone No : " 
		read ph
		echo "$ph" >> temp
		echo "$(tail +$r $1)" >> temp
		echo -e "\n\nDetails Updated "
		echo -e "\n\nPress Any Key To Continue "
		read ge
	;;

	8)
	;;

	*)
		echo -e "\nOops!! Invalid Input\n\nPress Any Key To Continue " 
		read gap
	;;

esac

if [ -f "temp" ];
then
	rm -r $1
	mv temp $1
fi

