#!/bin/bash
e=1

while [ $e -eq 1 ]
do
clear
echo -en "\n\t Customer Menu\n\n1. View Details\n2. Debit \n3. Credit \n4. Last 5 Debit \n5. Last 5 Credit \n6. Edit Phone No \n7. Edit E-mail \n8. Change Password \n9. Logout \n\nEnter Your Choice : "
read s

case $s in
1)
./custview $1
;;

2)
let " mon= 100000000000000 + $1"
clear
echo -en "\n\tDebit \n\nBalance : "
cat ./balance/$mon
bal=$(head -1 ./balance/$mon | tail +1 )
echo -en "\nEnter Amount :  "
read amm
if [[ "$bal" -gt "$amm" ]];
then 
let "bal = bal-amm"
echo "$bal" > ./balance/$mon
echo "Debit : $amm " >> $1
echo  -en "\nBalance : $bal\n\n***** Transaction Successfull *****"
read gi
else
echo  -en "\n***** Insufficent Balance *****"
read gi
fi 
;;

3)
let " mon= 100000000000000 + $1"
clear
echo -en "\n\tCredit \n\nBalance : "
cat ./balance/$mon
bal=$(head -1 ./balance/$mon | tail +1 )
echo -en "\nEnter Amount :  "
read amm
let "bal = bal+amm"
echo "$bal" > ./balance/$mon
echo "Credit : $amm " >> $1
echo  -en "\nBalance : $bal\n\n***** Transaction Successfull *****"
read gp
 
;;

4)
echo -e "\n\nLast 5 Debit \n"
tail -5 $1 | sed -n '/Debit/p'
read ga
;;

5)
echo -e "\n\nLast 5 Credit \n"
tail -5 $1 | sed -n '/Credit/p'
read ge
;;

6)
r=9
let "r--"
echo "$(head -$r $1)" >> temp
let "r=r+2"
echo -en "\nEnter Phone No : " 
read ph
echo "$ph" >> temp
echo "$(tail +$r $1)" >> temp
;;

7)
r=8
let "r--"
echo "$(head -$r $1)" >> temp
let "r=r+2"
echo -en "\nEnter Email : " 
read email
echo "$email" >> temp
echo "$(tail +$r $1)" >> temp
;;

8)
r=3
let "r--"
echo "$(head -$r $1)" >> temp
let "r=r+2"
echo -en "\nEnter Password : " 
read pas
echo "$pas" >> temp
echo "$(tail +$r $1)" >> temp

;;

9)
e=2
;;

*)
echo -e "\nOops!! Invalid Input" ;;

esac

if [ -f "temp" ];
then
rm -r $1
mv temp $1
fi
done
