#! /bin/bash


q=1
while [ $q -eq 1 ]
do
clear
echo -en "\n\t  _______                             _   _               __  __                  "
echo -en "\n\t |__   __|                           | | (_)             |  \/  |                 "
echo -en "\n\t    | |_ __ __ _ _ __  ___  __ _  ___| |_ _  ___  _ __   | \  / | ___ _ __  _   _ "
echo -en "\n\t    | |  __/ _  |  _ \/ __|/ _  |/ __| __| |/ _ \|  _ \  | |\/| |/ _ \  _ \| | | |"
echo -en "\n\t    | | | | (_| | | | \__ \ (_| | (__| |_| | (_) | | | | | |  | |  __/ | | | |_| |"
echo -en "\n\t    |_|_|  \__,_|_| |_|___/\__,_|\___|\__|_|\___/|_| |_| |_|  |_|\___|_| |_|\____|"
echo -en "\n\n\n1. Debit \n2. Credit \n3. Last 5 Debit \n4. Last 5 Credit \n5. Exit\n\nEnter Your Choice : "
read cs
dd=$(date)

case $cs in

	1)
		let " mon= 100000000000000 + $1"
		clear
		echo -en "\n\t  _____       _     _ _   "
		echo -en "\n\t |  __ \     | |   (_) |  "
		echo -en "\n\t | |  | | ___| |__  _| |_ "
		echo -en "\n\t | |  | |/ _ \  _ \| | __|"
		echo -en "\n\t | |__| |  __/ |_) | | |_ "
		echo -en "\n\t |_____/ \___|____/|_|\__|"
		echo -en "\n\n\nBalance : "
		cat ./balance/$mon
		bal=$(head -1 ./balance/$mon | tail +1 )
		echo -en "\nEnter Amount :  "
		read amm
		if [[ "$bal" -gt "$amm+500" ]];
		then 
			let "bal = bal-amm"
			echo "$bal" > ./balance/$mon
			echo -e "$amm \t| Debit \t| $dd " >> $1
			echo -e "\nWait for 1 min "
			echo -en "You have Debited $amm Rs from your Bank Account at $dd .\nCurrent Balance : $bal .\n\nFor Further Enquires ,Please Visit Branch\nThank-you For Choosing Our Bank\n\n\n*****This Mail is Automatically Generated *****" | mail -s "Money Debited " $(head -n 8 $1 | tail -n +8 )
			echo  -en "\nBalance : $bal\n\n***** Transaction Successfull *****"
			echo -e "\n\nPress Any Key To Continue "
			read gi
		else
			echo  -en "\n***** Insufficent Balance *****"
			echo -e "\n\nPress Any Key To Continue "
			read gi
		fi 
	;;

	2)
		let " mon= 100000000000000 + $1"
		clear
		echo -en "\n\t   _____              _ _ _   "
		echo -en "\n\t  / ____|            | (_) |  "
		echo -en "\n\t | |     _ __ ___  __| |_| |_ "
		echo -en "\n\t | |    |  __/ _ \/ _  | | __|"
		echo -en "\n\t | |____| | |  __/ (_| | | |_ "
		echo -en "\n\t  \_____|_|  \___|\__,_|_|\__|"
		echo -en "\n\n\nBalance : "
		cat ./balance/$mon
		bal=$(head -1 ./balance/$mon | tail +1 )
		echo -en "\nEnter Amount :  "
		read amm
		let "bal = bal+amm"
		echo "$bal" > ./balance/$mon
		echo -e "$amm \t| Credit \t| $dd " >> $1
		echo -e "\nWait for 1 min "
		echo -en "You have Credited $amm Rs in your Bank Account at $dd .\nCurrent Balance : $bal .\n\nFor Further Enquires ,Please Visit Branch\nThank-you For Choosing Our Bank\n\n\n*****This Mail is Automatically Generated *****" | mail -s "Money Credited " $(head -n 8 $1 | tail -n +8 )
		echo  -en "\nBalance : $bal\n\n***** Transaction Successfull *****"
		echo -e "\n\nPress Any Key To Continue "
		read gp
		 
	;;

	3)
		clear
		
		echo -en "\n\t  _               _     _____   _____       _     _ _   "
		echo -en "\n\t | |             | |   | ____| |  __ \     | |   (_) |  "
		echo -en "\n\t | |     __ _ ___| |_  | |__   | |  | | ___| |__  _| |_ "
		echo -en "\n\t | |    / _  / __| __| |___ \  | |  | |/ _ \  _ \| | __|"
		echo -en "\n\t | |___| (_| \__ \ |_   ___) | | |__| |  __/ |_) | | |_ "
		echo -en "\n\t |______\____|___/\__| |____/  |_____/ \___|____/|_|\__|"
		echo -e "\n\n\nAmmount \t: Date \n"
		sed -n '/Debit/p'  $1 | tail -5 | awk 'BEGIN{ FS="|" ; OFS="\t:" }{ print $1,$3 }'
		echo -e "\n\nPress Any Key To Continue "
		read ga
	;;

	4)
		clear
		echo -en "\n\t  _               _     _____    _____              _ _ _   "
		echo -en "\n\t | |             | |   | ____|  / ____|            | (_) |  "
		echo -en "\n\t | |     __ _ ___| |_  | |__   | |     _ __ ___  __| |_| |_ "
		echo -en "\n\t | |    / _  / __| __| |___ \  | |    |  __/ _ \/ _  | | __|"
		echo -en "\n\t | |___| (_| \__ \ |_   ___) | | |____| | |  __/ (_| | | |_ "
		echo -en "\n\t |______\____|___/\__| |____/   \_____|_|  \___|\____|_|\__|"
		echo -e "\n\n\nAmmount \t: Date \n"
		sed -n '/Credit/p' $1 | tail -5 | awk 'BEGIN{ FS="|" ; OFS="\t:" }{ print $1,$3 }'
		echo -e "\n\nPress Any Key To Continue "
		read ge
	;;
	5)
		q=0
	;;

	*)
		echo -e "\nOops!! Invalid Input\nPress Any Key To Continue " 
		read gap
	;;
esac

done






























